import * as THREE from 'three';
export class Kart {
  constructor(character,isPlayer=false){this.character=character;this.isPlayer=isPlayer;this.speed=0;this.heading=0;this.lap=0;this.progress=0;this.previousProgress=0;this.finished=false;this.boost=100;this.mesh=this.makeMesh();}
  makeMesh(){const kart=new THREE.Group();const paint=new THREE.MeshStandardMaterial({color:this.character.color,roughness:.28,metalness:.25}),black=new THREE.MeshStandardMaterial({color:0x15171b,roughness:.75}),skin=new THREE.MeshStandardMaterial({color:0xe8ae82}),shirt=new THREE.MeshStandardMaterial({color:this.character.color});
    const body=new THREE.Mesh(new THREE.BoxGeometry(2.15,.42,3.35),paint);body.position.y=.62;kart.add(body);const nose=new THREE.Mesh(new THREE.BoxGeometry(1.72,.28,.7),paint);nose.position.set(0,.56,1.88);kart.add(nose);const bumper=new THREE.Mesh(new THREE.BoxGeometry(2.38,.16,.22),black);bumper.position.set(0,.43,2.23);kart.add(bumper);const spoiler=new THREE.Mesh(new THREE.BoxGeometry(1.8,.16,.35),paint);spoiler.position.set(0,1.32,-1.5);kart.add(spoiler);for(const x of [-.9,.9]){const post=new THREE.Mesh(new THREE.BoxGeometry(.1,.7,.1),black);post.position.set(x,1.02,-1.43);kart.add(post)}
    const seat=new THREE.Mesh(new THREE.BoxGeometry(1.1,.66,1.05),black);seat.position.set(0,1.0,-.22);kart.add(seat);for(const x of [-.92,.92])for(const z of [-1.12,1.18]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.3,12),black);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.4,z);wheel.userData.wheel=true;kart.add(wheel)}
    const torso=new THREE.Mesh(new THREE.CylinderGeometry(.34,.45,.8,8),shirt);torso.position.set(0,1.55,-.1);kart.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.36,10,8),skin);head.position.set(0,2.2,-.03);kart.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(.38,10,6,0,Math.PI*2,0,Math.PI/2),black);hair.position.set(0,2.28,-.03);kart.add(hair);for(const x of [-.38,.38]){const arm=new THREE.Mesh(new THREE.CylinderGeometry(.1,.12,.65,7),skin);arm.position.set(x,1.55,.36);arm.rotation.z=x*.8;kart.add(arm);const leg=new THREE.Mesh(new THREE.CylinderGeometry(.13,.16,.7,7),black);leg.position.set(x*.65,1.0,.43);leg.rotation.x=Math.PI/2;kart.add(leg)}const steering=new THREE.Mesh(new THREE.TorusGeometry(.3,.05,7,12),black);steering.rotation.x=Math.PI/2;steering.position.set(0,1.36,.62);kart.add(steering);return kart;}
  reset(pos,heading){this.mesh.position.copy(pos);this.heading=heading;this.mesh.rotation.y=heading;this.speed=0;this.lap=0;this.finished=false;}
  updatePlayer(dt,input,track){const accel=this.character.acceleration*22,max=30*this.character.speed,forward=input.down('KeyW','ArrowUp'),backward=input.down('KeyS','ArrowDown'),boost=input.down('ShiftLeft','ShiftRight','Space')&&this.boost>0&&forward;if(forward)this.speed+=accel*dt;if(backward)this.speed-=accel*1.15*dt;if(!forward&&!backward)this.speed*=Math.pow(.55,dt);this.speed=Math.max(-9,Math.min(max+(boost?12:0),this.speed));if(boost)this.boost=Math.max(0,this.boost-31*dt);else this.boost=Math.min(100,this.boost+10*dt);const steer=(input.down('KeyA','ArrowLeft')?1:0)-(input.down('KeyD','ArrowRight')?1:0);this.heading+=steer*dt*2.25*Math.min(1,Math.abs(this.speed)/9)*(this.speed>=0?1:-1)*this.character.handling;this.move(dt,track);}
  updateAI(dt,track,target){const to=target.clone().sub(this.mesh.position),desired=Math.atan2(to.x,to.z);let delta=Math.atan2(Math.sin(desired-this.heading),Math.cos(desired-this.heading));this.heading+=Math.max(-1.7*dt,Math.min(1.7*dt,delta));this.speed=Math.min(25*this.character.speed,this.speed+15*dt);this.move(dt,track);}
  move(dt,track){const f=new THREE.Vector3(Math.sin(this.heading),0,Math.cos(this.heading));this.mesh.position.addScaledVector(f,this.speed*dt);const n=track.nearest(this.mesh.position);if(n.distance>track.spec.width*.57){this.mesh.position.copy(track.points[n.index]);this.speed*=.38}this.mesh.rotation.y=this.heading;this.mesh.traverse(o=>{if(o.userData.wheel)o.rotation.y-=this.speed*dt*2});this.previousProgress=this.progress;this.progress=n.progress;if(this.previousProgress>.88&&this.progress<.12&&this.speed>2)this.lap++;}
  score(){return this.finished?9999+this.lap:this.lap+this.progress;}
}
