import * as THREE from 'three'; import { Track } from './Track.js'; import { Kart } from './Kart.js';
export class Race { constructor({scene,camera,input,circuit,characters,onUpdate,onState}){this.scene=scene;this.camera=camera;this.input=input;this.track=new Track(scene,circuit);this.circuit=circuit;this.karts=characters.map((c,i)=>new Kart(c,i===0));this.karts.forEach(k=>scene.add(k.mesh));this.onUpdate=onUpdate;this.onState=onState;this.clock=new THREE.Clock();this.state='menu';this.elapsed=0;this.count=3;this.setup();}
 setup(){const p=this.track.point(0),t=this.track.curve.getTangentAt(0),heading=Math.atan2(t.x,t.z),side=new THREE.Vector3(-t.z,0,t.x);this.karts.forEach((k,i)=>k.reset(p.clone().addScaledVector(t,-5-i*3).addScaledVector(side,(i%2?1:-1)*2),heading));}
 start(){this.setup();this.state='countdown';this.count=3;this.elapsed=0;this.clock.start();this.onState('countdown',this.count);setTimeout(()=>this.tickCountdown(2),1000);}
 tickCountdown(n){if(this.state!=='countdown')return;this.count=n;if(n>0){this.onState('countdown',n);setTimeout(()=>this.tickCountdown(n-1),1000)}else{this.onState('go');this.state='racing';setTimeout(()=>{if(this.state==='racing')this.onState('clear')},750)}}
 update(){const dt=Math.min(this.clock.getDelta(),.05);if(this.state==='racing'){this.elapsed+=dt;this.karts[0].updatePlayer(dt,this.input,this.track);this.karts.slice(1).forEach((k,i)=>k.updateAI(dt,this.track,this.track.point(k.progress+.018+i*.001)));this.resolveKarts();const player=this.karts[0];if(player.lap>=this.circuit.laps){player.finished=true;this.state='finished';this.onState('finished',this.rankings());} } this.follow();this.onUpdate(this);}
 resolveKarts(){for(let i=0;i<this.karts.length;i++)for(let j=i+1;j<this.karts.length;j++){let a=this.karts[i],b=this.karts[j],d=a.mesh.position.distanceTo(b.mesh.position);if(d<2.1){const n=a.mesh.position.clone().sub(b.mesh.position).normalize();a.mesh.position.addScaledVector(n,.04);b.mesh.position.addScaledVector(n,-.04);a.speed*=.96;b.speed*=.96;}}}
 rankings(){return [...this.karts].sort((a,b)=>b.score()-a.score());}
 follow(){const p=this.karts[0].mesh.position,f=new THREE.Vector3(Math.sin(this.karts[0].heading),0,Math.cos(this.karts[0].heading));const wanted=p.clone().addScaledVector(f,-10).add(new THREE.Vector3(0,6,0));this.camera.position.lerp(wanted,.09);this.camera.lookAt(p.clone().addScaledVector(f,7).add(new THREE.Vector3(0,1,0)));}
}
