// Dependency-free Canvas 2.5D renderer: works from any ordinary static web server.
const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');document.querySelector('#app').prepend(canvas);
const $=s=>document.querySelector(s),keys=new Set();addEventListener('keydown',e=>{keys.add(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.code));
const track=[[-36,-8],[-27,-27],[-4,-34],[23,-28],[38,-8],[34,13],[17,28],[-8,31],[-29,20],[-40,5]].flatMap((p,i)=>{const q=[[-36,-8],[-27,-27],[-4,-34],[23,-28],[38,-8],[34,13],[17,28],[-8,31],[-29,20],[-40,5]][(i+1)%10];return Array.from({length:12},(_,j)=>[p[0]+(q[0]-p[0])*j/12,p[1]+(q[1]-p[1])*j/12])});
const racers=[['Garuda Muda','#e63946','🦅'],['Sari Pantai','#1976d2','🌺'],['Bima Hijau','#2a9d50','🌴'],['Dara Api','#f59e0b','🔥']].map((r,i)=>({name:r[0],color:r[1],avatar:r[2],player:i===0,p:i*.024-.04,speed:0,lap:0,boost:100,finished:false}));let state='menu',elapsed=0,last=performance.now(),countTimer=0;
function wrap(n){return(n%1+1)%1}function point(p){let n=track.length,x=wrap(p)*n,i=Math.floor(x),f=x-i,a=track[i],b=track[(i+1)%n];return[x=a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f]}function tangent(p){let a=point(p),b=point(p+.002);return Math.atan2(b[0]-a[0],b[1]-a[1])}function rank(){return [...racers].sort((a,b)=>(b.finished?999+b.lap:b.lap+b.p)-(a.finished?999+a.lap:a.lap+a.p))}
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function draw(){let w=innerWidth,h=innerHeight,me=racers[0],pos=point(me.p),ang=tangent(me.p);ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#74ccec');sky.addColorStop(.55,'#b8e6d4');sky.addColorStop(.56,'#5e9f4d');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='#496a53';ctx.beginPath();ctx.moveTo(0,h*.54);for(let x=0;x<=w;x+=80)ctx.lineTo(x,h*.35+Math.abs(Math.sin(x*.02))*90);ctx.lineTo(w,h*.58);ctx.fill();
 const project=([x,z])=>{let dx=x-pos[0],dz=z-pos[1],rx=dx*Math.cos(ang)-dz*Math.sin(ang),rz=dx*Math.sin(ang)+dz*Math.cos(ang);return [w/2+rx*15, h*.67-rz*9,rz]};
 // camera-follow road ribbon
 for(let i=-30;i<70;i++){let p1=point(me.p+i/track.length),p2=point(me.p+(i+1)/track.length),a=project(p1),b=project(p2),ta=tangent(me.p+i/track.length),tb=tangent(me.p+(i+1)/track.length),side=6;let al=project([p1[0]-Math.cos(ta)*side,p1[1]+Math.sin(ta)*side]),ar=project([p1[0]+Math.cos(ta)*side,p1[1]-Math.sin(ta)*side]),bl=project([p2[0]-Math.cos(tb)*side,p2[1]+Math.sin(tb)*side]),br=project([p2[0]+Math.cos(tb)*side,p2[1]-Math.sin(tb)*side]);ctx.fillStyle=i%2?'#30343b':'#363a41';ctx.beginPath();ctx.moveTo(al[0],al[1]);ctx.lineTo(ar[0],ar[1]);ctx.lineTo(br[0],br[1]);ctx.lineTo(bl[0],bl[1]);ctx.fill();if(i%4===0){ctx.strokeStyle='#f5f5ef';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(al[0],al[1]);ctx.lineTo(bl[0],bl[1]);ctx.moveTo(ar[0],ar[1]);ctx.lineTo(br[0],br[1]);ctx.stroke()}}
 racers.slice().sort((a,b)=>point(a.p)[1]-point(b.p)[1]).forEach(r=>{let q=project(point(r.p)),s=r.player?35:26;if(q[2]>-15&&q[2]<55){ctx.fillStyle='#111';ctx.fillRect(q[0]-s*.55,q[1]-s*.05,s*1.1,s*.5);ctx.fillStyle=r.color;ctx.beginPath();ctx.roundRect(q[0]-s*.6,q[1]-s*.7,s*1.2,s*.75,7);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 13px Outfit';ctx.textAlign='center';ctx.fillText(r.avatar+' '+r.name,q[0],q[1]-s*.95)}});}
function hud(){let me=racers[0],r=rank().indexOf(me)+1,t=elapsed,m=Math.floor(t/60),s=Math.floor(t%60),ms=Math.floor(t%1*1000);$('#position').innerHTML=`${r}<small>/4</small>`;$('#lap').textContent=`LAP ${Math.min(me.lap+1,3)}/3`;$('#speed').textContent=String(Math.round(Math.abs(me.speed)*8)).padStart(3,'0');$('#boost-fill').style.width=me.boost+'%';$('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`;let c=$('#map').getContext('2d');c.clearRect(0,0,170,130);c.strokeStyle='#f5c541';c.lineWidth=4;c.beginPath();track.forEach(([x,z],i)=>i?c.lineTo(85+x*1.3,65+z*1.3):c.moveTo(85+x*1.3,65+z*1.3));c.closePath();c.stroke();racers.forEach(k=>{let [x,z]=point(k.p);c.fillStyle=k.player?'#e63946':'#fff';c.beginPath();c.arc(85+x*1.3,65+z*1.3,k.player?5:3,0,7);c.fill()})}
function finish(){state='finished';let ranks=rank();$('#result-list').innerHTML=ranks.map((r,i)=>`<li class="${r.player?'me':''}"><b>${i+1}</b><span>${r.avatar} ${r.name}</span><em>${r.player?'ANDA':'AI'}</em></li>`).join('');$('#results').classList.remove('hidden')}
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(state==='countdown'){countTimer-=dt;if(countTimer<=0){state='racing';$('#countdown').textContent='GO!';setTimeout(()=>$('#countdown').classList.remove('show'),700)}}else if(state==='racing'){elapsed+=dt;let p=racers[0],go=keys.has('KeyW')||keys.has('ArrowUp'),back=keys.has('KeyS')||keys.has('ArrowDown'),boost=(keys.has('Space')||keys.has('ShiftLeft')||keys.has('ShiftRight'))&&go&&p.boost>0;p.speed+=(go?22:back?-25:-p.speed*3)*dt;p.speed=Math.max(-7,Math.min(boost?42:30,p.speed));if(boost)p.boost=Math.max(0,p.boost-30*dt);else p.boost=Math.min(100,p.boost+10*dt);p.p+=p.speed/1100*dt;if((keys.has('KeyA')||keys.has('ArrowLeft')))p.p-=.00035*Math.abs(p.speed);if((keys.has('KeyD')||keys.has('ArrowRight')))p.p+=.00035*Math.abs(p.speed);racers.slice(1).forEach((r,i)=>r.p+=(22+i*1.2)/1100*dt);racers.forEach(r=>{let was=wrap(r.p-r.speed/1100*dt)>.9&&wrap(r.p)<.1;if(was)r.lap++;if(r.player&&r.lap>=3&&!r.finished){r.finished=true;finish()}});hud()}draw();requestAnimationFrame(loop)}
function start(){racers.forEach((r,i)=>Object.assign(r,{p:i*.024-.04,speed:0,lap:0,boost:100,finished:false}));elapsed=0;state='countdown';countTimer=3;$('#countdown').textContent='3';$('#countdown').classList.add('show');let n=3;let timer=setInterval(()=>{if(state!=='countdown')return clearInterval(timer);n--;if(n>0)$('#countdown').textContent=n},1000)}$('#start').onclick=()=>{$('#menu').classList.add('hidden');$('#hud').classList.remove('hidden');start()};$('#restart').onclick=()=>{$('#results').classList.add('hidden');start()};requestAnimationFrame(loop);
