import * as THREE from 'three';
import { characters } from './data/characters.js';
import { baliCircuit } from './data/circuits.js';
import { Input } from './game/Input.js';
import { Race } from './game/Race.js';
import { Hud } from './ui/Hud.js';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x68c8ed);scene.fog=new THREE.Fog(0x68c8ed,55,180);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,300);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;document.querySelector('#app').prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe9faff,0x315327,2.7));const sun=new THREE.DirectionalLight(0xffefc4,2.5);sun.position.set(35,55,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-80;sun.shadow.camera.right=80;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80;scene.add(sun);
const hud=new Hud();let race;let selectedCharacter=characters[0];function state(kind){const count=document.querySelector('#countdown');if(kind==='countdown'||kind==='go'){count.textContent=kind==='go'?'GO!':race.count;count.classList.add('show')}else if(kind==='clear')count.classList.remove('show');else if(kind==='finished'){count.classList.remove('show');document.querySelector('#results').classList.remove('hidden');document.querySelector('#result-list').innerHTML=race.rankings().map((k,i)=>`<li class="${k.isPlayer?'me':''}"><b>${i+1}</b><span>${k.character.avatar} ${k.character.name}</span><em>${k.isPlayer?'ANDA':'AI'}</em></li>`).join('')}}
race=new Race({scene,camera,input:new Input(),circuit:baliCircuit,characters:[selectedCharacter,...characters.filter(c=>c.id!==selectedCharacter.id)],onUpdate:r=>{hud.update(r);const k=r.karts[0];camera.fov=62+(k.boost<99?7:0);camera.updateProjectionMatrix()},onState:state});
function renderCharacters(){document.querySelector('#character-cards').innerHTML=characters.map(c=>`<article class="character-card ${c.id===selectedCharacter.id?'selected':''}" data-id="${c.id}"><b>${c.avatar} ${c.name}</b><span>${c.category}</span><div class="stats">Speed ${c.speed} · Acceleration ${c.acceleration} · Handling ${c.handling} · Boost ${c.boost}</div></article>`).join('');document.querySelectorAll('.character-card').forEach(card=>card.onclick=()=>{selectedCharacter=characters.find(c=>c.id===card.dataset.id);renderCharacters()})}document.querySelector('#choose-character').onclick=()=>{renderCharacters();document.querySelector('#menu').classList.add('hidden');document.querySelector('#character-select').classList.remove('hidden')};document.querySelector('#character-back').onclick=()=>{document.querySelector('#character-select').classList.add('hidden');document.querySelector('#menu').classList.remove('hidden')};document.querySelector('#choose-circuit').onclick=()=>alert('Bali Circuit tersedia pada prototype ini.');document.querySelector('#settings').onclick=()=>alert('Pengaturan akan tersedia pada tahap berikutnya.');document.querySelector('#start').onclick=()=>{race.karts[0].character=selectedCharacter;race.karts[0].character.color=selectedCharacter.color;document.querySelector('#menu').classList.add('hidden');document.querySelector('#hud').classList.remove('hidden');race.start()};document.querySelector('#restart').onclick=()=>{document.querySelector('#results').classList.add('hidden');race.start()};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.setAnimationLoop(()=>{race.update();renderer.render(scene,camera)});
